### PR TITLE
Fix el9-dnf build

### PR DESCRIPTION
**Pull request by yatsukhnenko**
Allow `dnf` to use any versions of package to  resolve dependencies correctly

### CODE REVIEW

**Comment by tillkruss** [comment]
@yatsukhnenko: Can you explain what's happening any why this solves it?

**Comment by yatsukhnenko** [comment]
@tillkruss I'm not absolutely sure what's going on there, but if I'm not mistaken the same `php-relay` package if used for different versions on PHP
```bash
[root@5ba49412f74e /]# dnf repoquery --requires php-relay
Last metadata expiration check: 0:06:33 ago on Sun Apr 23 11:50:22 2023.
/bin/sh
libzstd
lz4
openssl
php(api) = 20190902-64
php(api) = 20200930-64
php(api) = 20210902-64
php(api) = 20220829-64
php-igbinary
php-msgpack
```
 `dnf` considers first record `php(api) = 20190902-64` the best candidate to install and requires its dependencies

**Comment by tillkruss** [comment]
That's odd. Can you post the dependencies of "php-redis" as well as "php82-redis"?

**Comment by yatsukhnenko** [comment]
```bash
[root@5ba49412f74e /]# dnf repoquery --requires php-pecl-redis5.x86_64
Last metadata expiration check: 0:02:11 ago on Mon Apr 24 17:11:10 2023.
libc.so.6(GLIBC_2.14)(64bit)
liblz4.so.1()(64bit)
liblzf.so.1()(64bit)
libzstd.so.1()(64bit)
php(api) = 20220829-64
php(zend-abi) = 20220829-64
php-igbinary(x86-64)
php-json(x86-64)
php-msgpack(x86-64)
rtld(GNU_HASH)
```

**Comment by yatsukhnenko** [comment]
Also `dnf info` shows 5 packages for `php-relay` and only 1 for `php-pecl-redis5`

**Comment by yatsukhnenko** [comment]
That's what I meant
```bash
[root@5ba49412f74e /]# dnf info php-relay
Last metadata expiration check: 0:02:58 ago on Mon Apr 24 17:11:10 2023.
Available Packages
Name         : php-relay
Version      : 0.6.3
Release      : 1
Architecture : aarch64
Size         : 2.1 M
Source       : php-relay-0.6.3-1.src.rpm
Repository   : cachewerk-el
Summary      : The next-generation caching layer for PHP.
URL          : https://relay.so
License      : Proprietary
Description  : The next-generation caching layer for PHP.

Name         : php-relay
Version      : 0.6.3
Release      : 1
Architecture : aarch64
Size         : 2.9 M
Source       : php-relay-0.6.3-1.src.rpm
Repository   : cachewerk-el
Summary      : The next-generation caching layer for PHP.
URL          : https://relay.so
License      : Proprietary
Description  : The next-generation caching layer for PHP.

Name         : php-relay
Version      : 0.6.3
Release      : 1
Architecture : x86_64
Size         : 2.1 M
Source       : php-relay-0.6.3-1.src.rpm
Repository   : cachewerk-el
Summary      : The next-generation caching layer for PHP.
URL          : https://relay.so
License      : Proprietary
Description  : The next-generation caching layer for PHP.

Name         : php-relay
Version      : 0.6.3
Release      : 1
Architecture : x86_64
Size         : 2.9 M
Source       : php-relay-0.6.3-1.src.rpm
Repository   : cachewerk-el
Summary      : The next-generation caching layer for PHP.
URL          : https://relay.so
License      : Proprietary
Description  : The next-generation caching layer for PHP.

Name         : php-relay
Version      : 0.6.3
Release      : 1
Architecture : x86_64
Size         : 3.0 M
Source       : php-relay-0.6.3-1.src.rpm
Repository   : cachewerk-el
Summary      : The next-generation caching layer for PHP.
URL          : https://relay.so
License      : Proprietary
Description  : The next-generation caching layer for PHP.

```

**Comment by yatsukhnenko** [comment]
```bash
[root@5ba49412f74e /]# dnf info php-pecl-redis5
Last metadata expiration check: 0:19:45 ago on Mon Apr 24 17:11:10 2023.
Available Packages
Name         : php-pecl-redis5
Version      : 5.3.7
Release      : 2.el9.remi.8.2
Architecture : x86_64
Size         : 274 k
Source       : php-pecl-redis5-5.3.7-2.el9.remi.8.2.src.rpm
Repository   : remi-modular
Summary      : Extension for communicating with the Redis key-value store
URL          : https://pecl.php.net/package/redis
License      : PHP
Description  : The phpredis extension provides an API for communicating
             : with the Redis key-value store.
             : 
             : This Redis client implements most of the latest Redis API.
             : As method only only works when also implemented on the server side,
             : some doesn't work with an old redis server version.
             : 
             : Package built for PHP 8.2.
```
@tillkruss all `php-relay` packages have the same `Version`. Is it ok?

**Comment by tillkruss** [comment]
I think none of the `single` installs are actually working.

**Comment by tillkruss** [comment]
@yatsukhnenko: I think the issue is we don't use modules, so `--nobest` seems like a valid approach. What do you think?

```bash
dnf module reset php
dnf module install php:remi-8.2
```

**Comment by yatsukhnenko** [comment]
> so --nobest seems like a valid approach

I think it should be possible to create separated releases for each PHP version the there wouldn't be conflicts but currently I don't know how to do this with FPM. Also I'm not familiar with the `dnf modules` and can't explain what are they until read some documentation 🤓

**Pull request closed without merging**
