### PR TITLE
Add EL9 Docker examples

### PR DESCRIPTION
**Pull request by tillkruss**
- [x] EL9 builds
- [x] EL9 docker examples
- [ ] EL9 repo

See https://github.com/cachewerk/linux-repos/pull/13

### CODE REVIEW

**Comment by aran112000** [comment]
Hi @tillkruss, thanks for your work adding RHEL9 support. We've just circled back around to try and add support again, however, the package doesn't appear to support up-to-date PHP versions (that is unless you're using them as multiple PHP installs which we aren't):

```bash
# dnf install php-relay
Last metadata expiration check: 0:02:39 ago on Wed 19 Apr 2023 21:50:16 BST.
Error: 
 Problem: package php-relay-0.6.3-1.x86_64 requires php(api) = 20190902-64, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package php-common-7.4.33-2.el9.remi.x86_64 is filtered out by modular filtering
  - package php-common-7.4.33-4.el9.remi.x86_64 is filtered out by modular filtering
```

```bash
# php -v
PHP 8.2.5 (cli) (built: Apr 11 2023 16:16:23) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies
```

If not already familiar, PHP 7.4 reached end of active support back in November 2021:
https://www.php.net/supported-versions.php

I've no idea what'd be involved in adding support for modern PHP versions, is this something that could be looked at?

**Comment by tillkruss** [comment]
Ah yes. We do provide builds for PHP 7.4, but Remi probably doesn't provide PHP repositories for 7.4 anymore. In that case I'd suggest using their paid LTS repositories, or installing Relay "manually", see the `el9.Dockerfile` example.

**Comment by aran112000** [comment]
Sorry, to clarify, we're not using 7.4, we're using 8.2

**Comment by tillkruss** [comment]
Ah, I see. The "simple install" with a single version is requiring PHP 7.4?

**Comment by tillkruss** [comment]
Let's move this here: https://github.com/cachewerk/linux-repos/issues/14

**Comment by aran112000** [comment]
> Ah, I see. The "simple install" with a single version is requiring PHP 7.4?

Yeah, that's correct. I'll follow the new issue you've opened, thank you for taking a look so quickly again.

**Pull request merged**
