### PR TITLE
chore: add opentelemetry example

### PR DESCRIPTION
**Pull request by vmihailenco**
I will continue working on this, but it is a decent preview of how it will look.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Regarding the instrumentation, I've noticed 2 things:
- `db.statement` attribute is missing which is rather useful to have
- looks like `$redis->multi()` and `$redis->pipeline()` require more work

@tillkruss I can try to address both issues, but wanted to check with you first.

**Comment by tillkruss** [comment]
Good catch, feel free to add both.

The db.statement could be extremely massive. I read somewhere that values should be omitted, just keys should be logged.

**Comment by vmihailenco** [comment]
I've sent https://github.com/cachewerk/relay/pull/32 to record `db.statement`, but `multi` and `pipeline` look somewhat complicated so we probably can leave it for later.

>I read somewhere that values should be omitted, just keys should be logged.

That recommendation only applies for span names. Attributes can be arbitrary large, for example, it is a common practice to record SQL queries which can be much larger than Redis commands.

**Comment by tillkruss** [comment]
I've done the `MULTI` wrapping in Object Cache Pro, will take a look today how it could be handled.

**Pull request closed without merging**
